GET http://localhost:3000/api/recipes
Content-Type: application/json

###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "testitesti",
    "name": "Vanessa",
    "password": "testi"
}

### Login Test
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "username": "olivia",
  "password": "testi"
}

### Save recipe test

POST http://localhost:3000/api/users/savedRecipe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjMxZmFmMDQzMWJmY2Y0YTExMDQwZiIsInVzZXJuYW1lIjoib2xpdmlhIiwiaWF0IjoxNzEwNTg4NTg2LCJleHAiOjE3MTA1OTIxODZ9.H4sO5ZQxNeYHP7qTa5R4eEMbODycJyrP0_3F-UuMesk

{
  "recipeId": "65f2ef9380e28358636a9137",
  "category": "jälkiruoka"
}

### Delete saved recipe

DELETE http://localhost:3000/api/users/savedRecipe
Content-Type: application/json

{
  "userId": "65f30f03613628ba90be9377",
  "recipeId": "65f2efaa80e28358636a98ff"
  
}

###

@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjMxZmFmMDQzMWJmY2Y0YTExMDQwZiIsInVzZXJuYW1lIjoib2xpdmlhIiwiaWF0IjoxNzEwNTg0MDg0LCJleHAiOjE3MTA1ODc2ODR9.p1oE1fRWE1PRvkmNrNRjMqaRE0-Pnb5g-nKjfNbC4BQ

### Get saved recipes
GET {{host}}/api/users/savedRecipe HTTP/1.1
Authorization: Bearer {{token}}
